require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SongRequestsController do

  def mock_song_request(stubs={})
    @mock_song_request ||= mock_model(SongRequest, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all song_requests as @song_requests" do
      SongRequest.stub(:all) { [mock_song_request] }
      get :index
      assigns(:song_requests).should eq([mock_song_request])
    end
  end

  describe "GET show" do
    it "assigns the requested song_request as @song_request" do
      SongRequest.stub(:find).with("37") { mock_song_request }
      get :show, :id => "37"
      assigns(:song_request).should be(mock_song_request)
    end
  end

  describe "GET new" do
    it "assigns a new song_request as @song_request" do
      SongRequest.stub(:new) { mock_song_request }
      get :new
      assigns(:song_request).should be(mock_song_request)
    end
  end

  describe "GET edit" do
    it "assigns the requested song_request as @song_request" do
      SongRequest.stub(:find).with("37") { mock_song_request }
      get :edit, :id => "37"
      assigns(:song_request).should be(mock_song_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created song_request as @song_request" do
        SongRequest.stub(:new).with({'these' => 'params'}) { mock_song_request(:save => true) }
        post :create, :song_request => {'these' => 'params'}
        assigns(:song_request).should be(mock_song_request)
      end

      it "redirects to the created song_request" do
        SongRequest.stub(:new) { mock_song_request(:save => true) }
        post :create, :song_request => {}
        response.should redirect_to(song_request_url(mock_song_request))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved song_request as @song_request" do
        SongRequest.stub(:new).with({'these' => 'params'}) { mock_song_request(:save => false) }
        post :create, :song_request => {'these' => 'params'}
        assigns(:song_request).should be(mock_song_request)
      end

      it "re-renders the 'new' template" do
        SongRequest.stub(:new) { mock_song_request(:save => false) }
        post :create, :song_request => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested song_request" do
        SongRequest.stub(:find).with("37") { mock_song_request }
        mock_song_request.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :song_request => {'these' => 'params'}
      end

      it "assigns the requested song_request as @song_request" do
        SongRequest.stub(:find) { mock_song_request(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:song_request).should be(mock_song_request)
      end

      it "redirects to the song_request" do
        SongRequest.stub(:find) { mock_song_request(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(song_request_url(mock_song_request))
      end
    end

    describe "with invalid params" do
      it "assigns the song_request as @song_request" do
        SongRequest.stub(:find) { mock_song_request(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:song_request).should be(mock_song_request)
      end

      it "re-renders the 'edit' template" do
        SongRequest.stub(:find) { mock_song_request(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested song_request" do
      SongRequest.stub(:find).with("37") { mock_song_request }
      mock_song_request.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the song_requests list" do
      SongRequest.stub(:find) { mock_song_request }
      delete :destroy, :id => "1"
      response.should redirect_to(song_requests_url)
    end
  end

end
